### Type definitions saved at 2020-02-10T06:10:20.654Z ###

type BankStateCityBranchesJson implements Node @derivedTypes @dontInfer {
  bank: String
  bankSlug: String
  state: String
  stateSlug: String
  city: String
  citySlug: String
  branches: [BankStateCityBranchesJsonBranches]
  type: String
}

type BankStateCityBranchesJsonBranches {
  label: String
  slug: String
}

type BankStateCitiesJson implements Node @derivedTypes @dontInfer {
  bank: String
  bankSlug: String
  state: String
  stateSlug: String
  cities: [BankStateCitiesJsonCities]
  type: String
}

type BankStateCitiesJsonCities {
  label: String
  slug: String
}

type BankStatesJson implements Node @derivedTypes @dontInfer {
  bank: String
  bankSlug: String
  states: [BankStatesJsonStates]
  type: String
}

type BankStatesJsonStates {
  label: String
  slug: String
}

type IfscJson implements Node @dontInfer {
  BANK: String
  IFSC: String
  BRANCH: String
  CENTRE: String
  DISTRICT: String
  STATE: String
  ADDRESS: String
  CONTACT: String
  IMPS: Boolean
  RTGS: Boolean
  CITY: String
  NEFT: Boolean
  MICR: String
  bankSlug: String
  stateSlug: String
  citySlug: String
  branchSlug: String
  type: String
}