### Type definitions saved at 2020-01-23T06:04:32.911Z ###

type IfscJson implements Node @derivedTypes @dontInfer {
  BANK: String
  IFSC: String
  BRANCH: String
  CENTRE: String
  DISTRICT: String
  STATE: String
  ADDRESS: String
  CONTACT: String
  IMPS: Boolean
  RTGS: Boolean
  CITY: String
  NEFT: Boolean
  MICR: String
  fields: IfscJsonFields
}

type IfscJsonFields {
  slug: String
  bankSlug: String
}