### Type definitions saved at 2019-12-27T11:59:30.553Z ###

type IfscCsv implements Node @derivedTypes @dontInfer {
  bank: String
  ifsc: String
  branch: String
  centre: String
  district: String
  state: String
  address: String
  contact: String
  imps: String
  rtgs: String
  city: String
  neft: String
  micr: String
  fields: IfscCsvFields
}

type IfscCsvFields {
  slug: String
}